apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-proxy-config
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-proxy.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "settings_production.py.proxy").AsSecrets | indent 2 }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-proxy-invscript
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-proxy.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "invscript_proxy.py").AsSecrets | indent 2 }} 


