apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsany-paas-proxy.fullname" . }}
  labels:
    {{- include "opsany-paas-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
      name: paas-proxy
  selector:
    {{- include "opsany-paas-proxy.selectorLabels" . | nindent 4 }}
