resources:
  - ../../base

namespace: opsany

commonLabels:
  app: opsany-proxy

images:
- name: opsany-proxy
  newName: registry.cn-beijing.aliyuncs.com/opsany/opsany-proxy
  newTag: 1.2.1

configMapGenerator:
- name: the-map
  literals:
    - altGreeting=Good Morning!
    - enableRisky="false"

patchesStrategicMerge:
- nfsserver_patch.yaml
