apiVersion: v1
kind: Secret
metadata:
  name: opsany-prometheus-config
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-prometheus.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "prometheus.yml").AsSecrets | indent 2 }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: opsany-prometheus-web-config
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-prometheus.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "web.yml").AsSecrets | indent 2 }} 
