---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsany-prometheus-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/consul-volume/data
    server: 10.224.218.71

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsany-prometheus-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: opsany-prometheus-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsany-prometheus-rules
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/opsany-uploads/prometheus-config/rules
    server: 10.224.218.71

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsany-prometheus-rules
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: opsany-prometheus-rules
