apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-appengine-config
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-appengine.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "settings_production.py.appengine").AsSecrets | indent 2 }} 

---

apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-appengine-supervisor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opsany-paas-appengine.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "appengine.ini").AsSecrets | indent 2 }}
