apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsany-paas-appengine.fullname" . }}
  labels:
    {{- include "opsany-paas-appengine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: paas-appengine
  selector:
    {{- include "opsany-paas-appengine.selectorLabels" . | nindent 4 }}
