---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsany-paas-login
  namespace: opsany
spec:
  selector: 
    matchLabels:
      app: opsany-paas-login
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: IfNotPresent
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opsany-paas-login
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.login.name }}:{{ .Values.image.login.tag }}"
        name: login
        ports:
        - name: login
          containerPort: 8003
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 10

        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - mountPath: /opt/opsany/paas/login/conf/settings_production.py
          name: paas-login-cm
          subPath: settings_production.py
        - name: paas-login-logs
          mountPath: /opt/opsany/logs
    
      volumes:
        - name: paas-login-cm
          configMap:
            name: paas-login-cm
            items:
            - key: settings_production.py
              path: settings_production.py
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: paas-login-logs
          persistentVolumeClaim:
            claimName: paas-login-logs-pvc

      

