apiVersion: v1
kind: Service
metadata:
  name: opsany-paas-login
  namespace: opsany
  annotations: {}
spec:
  ports:
  - name: http
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: opsany-paas-login


