---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paas-login-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /opsany/logs
    server: "{{ .Values.nfsServer.server }}"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paas-login-logs-pvc
  namespace: opsany
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: paas-login-pv
