apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsany-paas-websocket.fullname" . }}
  labels:
    {{- include "opsany-paas-websocket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8004
      protocol: TCP
      name: websocket
  selector:
    {{- include "opsany-paas-websocket.selectorLabels" . | nindent 4 }}
