---
# nginx.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-paas-openresty-nginx
data:
{{ (.Files.Glob "nginx.conf").AsConfig | indent 2 }}

---
# nginx_paas.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-paas-openresty-paas
data:
{{ (.Files.Glob "opsany_paas.conf").AsConfig | indent 2 }}

---
# nginx_proxy.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-paas-openresty-proxy
data:
{{ (.Files.Glob "opsany_proxy.conf").AsConfig | indent 2 }}

