# ssl
apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-ingress-tls
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-openresty.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt:
    {{ .Files.Get "ssl/DOMAIN_NAME.pem" | b64enc }}
  tls.key:
    {{ .Files.Get "ssl/DOMAIN_NAME.key" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-openresty-ssl
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-openresty.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "ssl/*").AsSecrets | indent 2 }} 
