apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsany-paas-openresty.fullname" . }}
  labels:
    {{- include "opsany-paas-openresty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "opsany-paas-openresty.selectorLabels" . | nindent 4 }}
