---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsany-logs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/opsany-logs
    server: LOCAL_IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsany-logs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: opsany-logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsany-uploads
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/opsany-uploads
    server: LOCAL_IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsany-uploads
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: opsany-uploads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsany-paas-esb-code
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/opsany-esb-code
    server: LOCAL_IP
---
# Source: paas-install/templates/paas-paas-storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsany-paas-esb-code
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: opsany-paas-esb-code
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsany-paas-grafana-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/opsany-grafana-data
    server: LOCAL_IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsany-paas-grafana-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: opsany-paas-grafana-data
