---
# job-init.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-job-init
data:
{{ (.Files.Glob "job-init.py").AsConfig | indent 2 }}

---
# job-prod.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-job-prod
data:
{{ (.Files.Glob "job-prod.py").AsConfig | indent 2 }}

---
# job-nginx.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-job-nginx
data:
{{ (.Files.Glob "job-nginx.conf").AsConfig | indent 2 }}

---
# job-supervisor.ini
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-job-supervisor
data:
{{ (.Files.Glob "job-supervisor.ini").AsConfig | indent 2 }}

---
# job-uwsgi.ini
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-job-uwsgi
data:
{{ (.Files.Glob "job-uwsgi.ini").AsConfig | indent 2 }}
