---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paas-proxy-cm
  namespace: opsany
data:
  prod.py: |
{{ .Files.Get "files/opsany/conf/proxy/settings_production.py.proxy" | indent 4 }}
  invscript_proxy.py: |
{{ .Files.Get "files/opsany/conf/proxy/invscript_proxy.py" | indent 4 }}
