---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsany-proxy
  namespace: opsany
spec:
  selector: 
    matchLabels:
      app: opsany-proxy
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: opsany-proxy
    spec:
      imagePullSecrets: []
      containers:
      - image: ""
        name: opsany-proxy
        ports:
        - name: tcp-salt0
          containerPort: 4505
          protocol: TCP
        - name: tcp-salt1
          containerPort: 4506
          protocol: TCP
        - name: http
          containerPort: 8010
          protocol: TCP


        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - mountPath: /opt/opsany-proxy/config/prod.py 
          name: proxy-prod
          subPath: prod.py
        - mountPath: /opt/opsany-proxy/invscript_proxy.py
          name: proxy-invs
          subPath: invscript_proxy.py
        - name: proxy-logs
          mountPath: /opt/opsany/logs
        - name: proxy-certs
          mountPath: /etc/pki/tls/certs
        - name: proxy-salt
          mountPath: /etc/salt
        - name: proxy-cache
          mountPath: /var/cache/salt
        - name: proxy-srv
          mountPath: /srv/salt
        - name: proxy-pillar
          mountPath: /srv/pillar
        - name: proxy-playbook
          mountPath: /srv/playbook
        - name: proxy-uploads
          mountPath: /opt/opsany/uploads
        - name: proxy-pki
          mountPath: /opt/opsany/pki
    
      volumes:
        - name: proxy-prod
          configMap:
            name: paas-proxy-cm
            items:
            - key: prod.py
              path: prod.py
        - name: proxy-invs
          configMap:
            name: paas-proxy-cm
            items:
            - key: invscript_proxy.py
              path: invscript_proxy.py
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: proxy-logs
          persistentVolumeClaim:
            claimName: paas-proxy-logs-pvc
        - name: proxy-certs
          persistentVolumeClaim:
            claimName: paas-proxy-logs-pvc
        - name: proxy-salt
          persistentVolumeClaim:
            claimName: paas-proxy-salt-pvc
        - name: proxy-cache
          persistentVolumeClaim:
            claimName: paas-proxy-cache-pvc
        - name: proxy-srv
          persistentVolumeClaim:
            claimName: paas-proxy-srv-pvc
        - name: proxy-pillar
          persistentVolumeClaim:
            claimName: paas-proxy-pillar-pvc
        - name: proxy-playbook
          persistentVolumeClaim:
            claimName: paas-proxy-playbook-pvc
        - name: proxy-uploads
          persistentVolumeClaim:
            claimName: paas-proxy-uploads-pvc
        - name: proxy-pki
          persistentVolumeClaim:
            claimName: paas-proxy-pki-pvc
