apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-esb-conf
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-esb.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "settings_production.py.esb").AsSecrets | indent 2 }} 

---

apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-esb-supervisor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opsany-paas-esb.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "esb.ini").AsSecrets | indent 2 }}
