apiVersion: v1
kind: Service
metadata:
  name: opsany-paas-paasagent
  namespace: opsany
  annotations: {}
spec:
  ports:
  - name: http
    port: 4245
    protocol: TCP
    targetPort: 4245
  - name: htt
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: opsany-paas-paasagent


