---
# kbase-init.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-kbase-init
data:
{{ (.Files.Glob "kbase-init.py").AsConfig | indent 2 }}

---
# kbase-prod.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-kbase-prod
data:
{{ (.Files.Glob "kbase-prod.py").AsConfig | indent 2 }}

---
# kbase-nginx.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-kbase-nginx
data:
{{ (.Files.Glob "kbase-nginx.conf").AsConfig | indent 2 }}

---
# kbase-supervisor.ini
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-kbase-supervisor
data:
{{ (.Files.Glob "kbase-supervisor.ini").AsConfig | indent 2 }}

---
# kbase-uwsgi.ini
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-kbase-uwsgi
data:
{{ (.Files.Glob "kbase-uwsgi.ini").AsConfig | indent 2 }}
