apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opsany-paas-paas.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-paas.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "settings_production.py.paas").AsSecrets | indent 2 }} 
