apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-paas-config
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-paas.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "settings_production.py.paas").AsSecrets | indent 2 }} 

---
apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-paas-supervisor
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-paas.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "paas.ini").AsSecrets | indent 2 }} 
