apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsany-paas-paas.fullname" . }}
  labels:
    {{- include "opsany-paas-paas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
      protocol: TCP
      name: paas-paas
  selector:
    {{- include "opsany-paas-paas.selectorLabels" . | nindent 4 }}
