---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsany-paas-paas-logs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: {{ .Values.volume.path }}
    server: {{ .Values.volume.server }}
---
# Source: paas-install/templates/paas-paas-storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsany-paas-paas-logs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: opsany-paas-paas-logs

