---
# deploy-init.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-deploy-init
data:
{{ (.Files.Glob "deploy-init.py").AsConfig | indent 2 }}

---
# deploy-prod.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-deploy-prod
data:
{{ (.Files.Glob "deploy-prod.py").AsConfig | indent 2 }}

---
# deploy-nginx.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-deploy-nginx
data:
{{ (.Files.Glob "deploy-nginx.conf").AsConfig | indent 2 }}

---
# deploy-supervisor.ini
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-deploy-supervisor
data:
{{ (.Files.Glob "deploy-supervisor.ini").AsConfig | indent 2 }}

---
# deploy-uwsgi.ini
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ee-deploy-uwsgi
data:
{{ (.Files.Glob "deploy-uwsgi.ini").AsConfig | indent 2 }}
