---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertscripts
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/zabbix-volume/alertscripts
    server: LOCAL_IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertscripts
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: alertscripts


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: externalscripts
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/zabbix-volume/externalscripts
    server: LOCAL_IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: externalscripts
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: externalscripts


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: snmptraps
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
  nfs:
    path: /data/k8s-nfs/zabbix-volume/snmptraps
    server: LOCAL_IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snmptraps
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: snmptraps
