apiVersion: v1
kind: Service
metadata:
  name: opsany-paas-paas
  namespace: opsany
  annotations: {}
spec:
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: opsany-paas-paas


