apiVersion: v1
kind: Secret
metadata:
  name: opsany-consul-config
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-consul.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "consul.hcl").AsSecrets | indent 2 }} 
