apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsany-consul.fullname" . }}
  labels:
    {{- include "opsany-consul.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8500
      protocol: TCP
      name: http
  selector:
    {{- include "opsany-consul.selectorLabels" . | nindent 4 }}
