---
# pipeline-init.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-pipeline-init
data:
{{ (.Files.Glob "pipeline-init.py").AsConfig | indent 2 }}

---
# pipeline-prod.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-pipeline-prod
data:
{{ (.Files.Glob "pipeline-prod.py").AsConfig | indent 2 }}

---
# pipeline-nginx.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-pipeline-nginx
data:
{{ (.Files.Glob "pipeline-nginx.conf").AsConfig | indent 2 }}

---
# pipeline-supervisor.ini
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-pipeline-supervisor
data:
{{ (.Files.Glob "pipeline-supervisor.ini").AsConfig | indent 2 }}

---
# pipeline-uwsgi.ini
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsany-saas-ce-pipeline-uwsgi
data:
{{ (.Files.Glob "pipeline-uwsgi.ini").AsConfig | indent 2 }}
