apiVersion: v1
kind: Service
metadata:
  name: opsany-paas-esb
  namespace: opsany
  annotations: {}
spec:
  ports:
  - name: http
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: opsany-paas-esb


