apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsany-paas-grafana.fullname" . }}
  labels:
    {{- include "opsany-paas-grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: grafana
  selector:
    {{- include "opsany-paas-grafana.selectorLabels" . | nindent 4 }}
