---
apiVersion: v1
kind: ConfigMap
metadata:
  name: websocket-cm
  namespace: opsany
data:
  prod.py: |
{{ .Files.Get "files/opsany/conf/settings_production.py.websocket" | indent 4 }}
  __init__.py: |
{{ .Files.Get "files/opsany/conf/settings_production.py.websocket.init" | indent 4 }}
