---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsany-websocket
  namespace: opsany
spec:
  selector: 
    matchLabels:
      app: opsany-websocket
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: IfNotPresent
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opsany-websocket
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.websocket.name }}:{{ .Values.image.websocket.tag }}"
        name: websocket
        ports:
        - name: websocket
          containerPort: 8004
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8004
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8004
          initialDelaySeconds: 15
          periodSeconds: 10

        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - mountPath: /opt/opsany/websocket/config/prod.py
          name: websocket-conf
          subPath: prod.py
        - mountPath: /opt/opsany/websocket/config/__init__.py
          name: websocket-init
          subPath: __init__.py
        - name: websocket-logs
          mountPath: /opt/opsany/logs
    
      volumes:
        - name: websocket-conf
          configMap:
            name: websocket-cm
            items:
            - key: prod.py
              path: prod.py
        - name: websocket-init
          configMap:
            name: websocket-cm
            items:
            - key: __init__.py
              path: __init__.py
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: websocket-logs
          persistentVolumeClaim:
            claimName: websocket-logs-pvc

      imagePullSecrets:
      - name: opsany-secret
      

