apiVersion: v1
kind: Service
metadata:
  name: opsany-websocket
  namespace: opsany
  annotations: {}
spec:
  ports:
  - name: http
    port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: opsany-websocket


