---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsany-paas-appengine
  namespace: opsany
spec:
  selector: 
    matchLabels:
      app: opsany-paas-appengine
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: IfNotPresent
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opsany-paas-appengine
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.appengine.name }}:{{ .Values.image.appengine.tag }}"
        name: appengine
        ports:
        - name: appengine
          containerPort: 8000
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10

        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - mountPath: /opt/opsany/paas/appengine/controller/settings.py
          name: paas-appengine-cm
          subPath: settings.py
        - name: paas-appengine-logs
          mountPath: /opt/opsany/logs
    
      volumes:
        - name: paas-appengine-cm
          configMap:
            name: paas-appengine-cm
            items:
            - key: settings.py
              path: settings.py
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: paas-appengine-logs
          persistentVolumeClaim:
            claimName: paas-appengine-logs-pvc

      

