apiVersion: v1
kind: Service
metadata:
  name: opsany-paas-appengine
  namespace: opsany
  annotations: {}
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: opsany-paas-appengine


