---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsany-grafana
  namespace: opsany
spec:
  selector: 
    matchLabels:
      app: opsany-grafana
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: IfNotPresent
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opsany-grafana
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.grafana.name }}:{{ .Values.image.grafana.tag }}"
        name: grafana
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - name: grafana
          containerPort: 3000
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10

        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: grafana-conf
          mountPath: /etc/grafana
        - name: grafana-data
          mountPath: /var/lib/grafana
    
      volumes:

        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: grafana-conf
          persistentVolumeClaim:
            claimName: grafana-conf-pvc
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data-pvc

      

