apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-login-config
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "opsany-paas-login.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "settings_production.py.login").AsSecrets | indent 2 }} 

---

apiVersion: v1
kind: Secret
metadata:
  name: opsany-paas-login-supervisor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opsany-paas-login.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "login.ini").AsSecrets | indent 2 }}
