apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsany-paas-login.fullname" . }}
  labels:
    {{- include "opsany-paas-login.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8003
      protocol: TCP
      name: paas-login
  selector:
    {{- include "opsany-paas-login.selectorLabels" . | nindent 4 }}
